### ISSUE TITLE
parser transformation bugs

### ISSUE THREAD

**Issue by pickettj** [pickettj/xml_development_eurasia#6]
Lingering parser bugs:

- No closing tag for `<div>`
- `<lb/>` has an extra tag at the beginning (i.e. before the text of each section begins), and lacks one at the end of the section.

**Comment by pickettj** [comment]
@iamlemec , I'm puzzled by the fact that my [Jupyter parser](https://github.com/pickettj/xml_development_eurasia/blob/master/markdown_parser/markdown_parser_3.0.ipynb) works great (even fixed above bugs); but when I run the Python file from command line (i.e. exported from the Jupyter notebook) I get an error message...:

```
Traceback (most recent call last):
  File "/Users/kribblesworth/Projects/xml_development_eurasia/markdown_parser/markdown_parser_3.0.py", line 29, in <module>
    import parser_functions as pf
  File "/Users/kribblesworth/Projects/xml_development_eurasia/markdown_parser/parser_functions.py", line 52
    body = '\n'.join([f'\t{s}' for s in conv.split('\n')])
```

**Comment by iamlemec** [comment]
That import works fine for me. What's the entire error message? Need to know the specific error it's throwing.

**Comment by pickettj** [comment]
That's everything but a syntax error at the end:

![image](https://user-images.githubusercontent.com/25989796/73017656-304bb480-3dee-11ea-9ae8-25bc1db818a5.png)

**Comment by iamlemec** [comment]
One possibility is that you're running this with an interpreter of version 3.5 or earlier, when there were no f-strings. How are you calling python in md_parse and what version would that be?

**Comment by pickettj** [comment]
Ah. `Python 2.7.16`. That seems an astute diagnosis.

So I guess I basically just need to run it with python3, which is also installed (Python 3.7.3)? Thanks @iamlemec
