### ISSUE TITLE
linebreaks from <lb>

### ISSUE THREAD

**Issue by pickettj** [pickettj/xml_development_eurasia#8]
@djbpitt , any breadcrumbs for the following?

I use a milestone element `<lb/>`, i.e. line beginning from TEI. How would you get from there to a line break (which comes at the end of the line in HTML)?

[Current code](https://github.com/pickettj/xml_development_eurasia/blob/master/xslt/persian_document_reading_view_basic.xsl) (resulting in an extra line at the beginning, and missing a break at the end):

```xslt
    <xsl:template match="lb">
        <span class = "numeration">(<xsl:value-of select="count(preceding-sibling::lb)+1"/>)</span>
        <br/>
    </xsl:template>
```

**Comment by djbpitt** [comment]
@pickettj Can you upload a small XML sample that you want to process and an example of the output you want from it?

**Comment by pickettj** [comment]
@djbpitt , here's a [fairly typical document](https://github.com/pickettj/xml_development_eurasia/blob/master/reading_views/example.xml) for which I use this transformation.

**Comment by pickettj** [comment]
And the [reading views directory](https://github.com/pickettj/xml_development_eurasia/tree/master/reading_views) has sample outputs produced from the XSLT.

**Comment by djbpitt** [comment]
@pickettj Have I understood correctly that you want to extract the lines from the source document? If so, do you need any markup, or do you just want the text (string-value) of the lines?

**Comment by pickettj** [comment]
@djbpitt yes, I'm extracting the numbered lines from the source document, so that a <lb> goes to something like this:

![image](https://user-images.githubusercontent.com/25989796/72815164-385ff480-3c34-11ea-8de3-ca63ccd2e9bb.png)

(My CSS abruptly stopped working for reasons I am still trying to figure out... but this is the general idea.)

I use other markup in the XML for other things (e.g. coloring words differently by function); but that part already works fine with my current xslt. (And even the <lb> part *almost* works; the issue is that html linebreaks go at the end of the line, and my <lb> elements mark the beginning of the line; I was considering altering my [parser instead](https://github.com/pickettj/xml_development_eurasia/blob/master/markdown_parser/markdown_parser_3.0.py), but that would be tantamount to tag abuse, since it would effectively turn <lb> into a line break.)

**Comment by pickettj** [comment]
Thanks @djbpitt ! I [have an xslt](https://github.com/pickettj/xml_development_eurasia/blob/master/xslt/persian_document_reading_view_basic.xsl) that gets the job done, and produces a nice reading view.
